theme: jekyll-theme-cayman

# Setup
title:        IIPC Community Resources
tagline:      IIPC Community Resources
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       IIPC
  url:        http://netpreserve.org

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

